// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC1CywljiQi8drajZ0ge15GxYLlMJZbQs',
    appId: '1:966955193555:web:060d13c31334666b5cf026',
    messagingSenderId: '966955193555',
    projectId: 'sme-movies-app-9ca8e',
    authDomain: 'sme-movies-app-9ca8e.firebaseapp.com',
    storageBucket: 'sme-movies-app-9ca8e.appspot.com',
    measurementId: 'G-4XDNE0SZHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFDuc3neOGlxdI_EH1H-AS243aemDGEuw',
    appId: '1:966955193555:android:41cd9be5100e3cac5cf026',
    messagingSenderId: '966955193555',
    projectId: 'sme-movies-app-9ca8e',
    storageBucket: 'sme-movies-app-9ca8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIyqxHmCZuWDN8PG9r-Gxeuj2DPDMHfpA',
    appId: '1:966955193555:ios:81c449d81925b7cf5cf026',
    messagingSenderId: '966955193555',
    projectId: 'sme-movies-app-9ca8e',
    storageBucket: 'sme-movies-app-9ca8e.appspot.com',
    iosBundleId: 'com.example.smeMoviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIyqxHmCZuWDN8PG9r-Gxeuj2DPDMHfpA',
    appId: '1:966955193555:ios:81c449d81925b7cf5cf026',
    messagingSenderId: '966955193555',
    projectId: 'sme-movies-app-9ca8e',
    storageBucket: 'sme-movies-app-9ca8e.appspot.com',
    iosBundleId: 'com.example.smeMoviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC1CywljiQi8drajZ0ge15GxYLlMJZbQs',
    appId: '1:966955193555:web:92b19882babc3f2a5cf026',
    messagingSenderId: '966955193555',
    projectId: 'sme-movies-app-9ca8e',
    authDomain: 'sme-movies-app-9ca8e.firebaseapp.com',
    storageBucket: 'sme-movies-app-9ca8e.appspot.com',
    measurementId: 'G-BD5XR9454F',
  );
}